name: Terraform Multi-Env Workflow

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch previous commit (safe fallback)
        run: |
          git fetch --depth=2 origin ${{ github.ref }}

      - name: Detect all changed Terraform envs
        id: set-matrix
        run: |
          base_sha=$(git rev-parse HEAD^ || git rev-parse HEAD)
          changed_files=$(git diff --name-only "$base_sha" HEAD | grep '^terraform/' || true)

          echo "Changed files:"
          echo "$changed_files"

          unique_paths=$(echo "$changed_files" | grep '^terraform/.*/.*/.*/' \
            | cut -d'/' -f2-4 \
            | sort -u \
            | jq -R -s -c 'split("\n") | map(select(. != "")) | map(split("/") | {app_name: .[0], aws_region: .[1], app_env: .[2]})')

          echo "matrix=$unique_paths" >> $GITHUB_OUTPUT
          echo "Matrix JSON: $unique_paths"

  terraform-plan:
    needs: find-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.find-changes.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "App: ${{ matrix.app_name }}"
          echo "Region: ${{ matrix.aws_region }}"
          echo "Env: ${{ matrix.app_env }}"
